[package]
name = "aismar"
version = "0.1.0"
edition = "2024"

[dependencies]
ais = "0.12.0"
anyhow = "1.0.97"
axum = "0.8.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.5.2"
